import type {Metadata} from "next"
import {Geist, Geist_Mono} from "next/font/google"
import localFont from "next/font/local"
import "./globals.css"
import {
	ClerkProvider,
	RedirectToSignIn,
	SignedIn,
	SignedOut,
	UserButton,
} from "@clerk/nextjs"
import ConvexClientProvider from "@/components/ConvexClientProvider"

const martianGrotesk = localFont({
	src: "./fonts/MartianGrotesk.woff2",
	variable: "--font-martian-grotesk",
})

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
})

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	icons: {
		icon: "/convex.svg",
	},
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${martianGrotesk.variable} antialiased`}
			>
				<ClerkProvider dynamic>
					<ConvexClientProvider>
						<SignedIn>
							<header className="sticky top-0 z-10 bg-bg p-4 border-b-2 border-slate-200 dark:border-slate-800 flex flex-row justify-between items-center">
								<UserButton />
							</header>
							{children}
						</SignedIn>
						<SignedOut>
							<RedirectToSignIn />
						</SignedOut>
					</ConvexClientProvider>
				</ClerkProvider>
			</body>
		</html>
	)
}
